- name: DEPLOY AS3 DECLARATION
  hosts: localhost
  connection: local
  gather_facts: no
  

  vars_files:
    ../creds.yaml

  vars:
    uri_method: POST

  tasks:
  - name: Create a JIRA issue
    uri:
      url: https://3.8.7.200//mgmt/shared/appsvcs/declare/
      user: "{{bigip_user}}"
      password: "{{bigip_pass}}"
      method: "{{uri_method}}"
          validate_certs: no
      body: "{{ lookup('file','./as3-dec.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json